[project]
name = "contour-toolpath"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=6.0.1",
    "pyright>=1.1.399",
    "trimesh>=4.6.8",
]


[tool.pyright]
typeCheckingMode = "strict"


